#Hospital Management System
patient_id=input("enter the patient id : " )
patient_name=input("enter the patient name : " )
age=int(input("enter patient age : " ))
blood_group=input("enter the blood group : " )
phone_number=int(input("enter your phone number : " ))
print("\ Patient Card")
print(f"patient_id : {patient_id}")
print(f"patient_name : {patient_name}")
print(f"age : {age}")
print(f"blood_group : {blood_group}")
print(f"phone_number : {phone_number}")
